[package]
name = "ciao"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ciao"
path = "src/main.rs"

[dependencies]
ciao-core = { path = "../ciao-core" }
clap.workspace = true
ctrlc.workspace = true
serde.workspace = true
serde_json.workspace = true
indicatif = { version = "0.17", default-features = false }
